python create_jobs.py -o job.Shenzhen.wgangp.v1.test_0.10_sorts -s 10 --xt 0
python create_jobs.py -o job.Shenzhen.wgangp.v1.test_1.10_sorts -s 10 --xt 1
python create_jobs.py -o job.Shenzhen.wgangp.v1.test_2.10_sorts -s 10 --xt 2
python create_jobs.py -o job.Shenzhen.wgangp.v1.test_3.10_sorts -s 10 --xt 3
python create_jobs.py -o job.Shenzhen.wgangp.v1.test_4.10_sorts -s 10 --xt 4
python create_jobs.py -o job.Shenzhen.wgangp.v1.test_5.10_sorts -s 10 --xt 5
python create_jobs.py -o job.Shenzhen.wgangp.v1.test_6.10_sorts -s 10 --xt 6
python create_jobs.py -o job.Shenzhen.wgangp.v1.test_7.10_sorts -s 10 --xt 7
python create_jobs.py -o job.Shenzhen.wgangp.v1.test_8.10_sorts -s 10 --xt 8
python create_jobs.py -o job.Shenzhen.wgangp.v1.test_9.10_sorts -s 10 --xt 9
